name: ci
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          rustflags: 
      - name: Run Tests
        run: cargo test --all-features
      - name: Check Clippy
        run: cargo clippy --all-features
      - name: Check Formatting
        run: cargo fmt --check